### ISSUE TITLE
Create Demo

### ISSUE THREAD

**Issue by tim-pugh** [clang-randstruct/llvm-project#25]
Need to create a demo video for our presentation

**Comment by tim-pugh** [comment]
Since people may fall asleep in our demo this music may keep them awake :)

https://www.youtube.com/watch?v=owq7hgzna3E

**Comment by jeffreytakahashi** [comment]
What do we need to 'see' in a demo? I feel like if it's just the terminal IO then we'd be better off just using screenshots because then we can at least explain with a static image rather than have it jumping around doing other things since all that we're doing is compiling a thing and seeing some output anyway.

**Comment by tim-pugh** [comment]
Its your task feel free tondo it as you see fit and report back.

**Comment by jeffreytakahashi** [comment]
I worked out slides and Nikk and James helped flesh them out and right now Nikk is working on the video demo.

**Comment by tim-pugh** [comment]
Looks like the demo is done so I'm closing this issue.
